### ISSUE TITLE
st-memory-calculator

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/silicon-toolkit#12]
Command line based functionality similar to what we have in graph form on the Tuning Advisor dashboard in SSM.

For theoretical maximum finite memory usage.
```
SELECT (
           (
               @@binlog_file_cache_size +
               @@innodb_buffer_pool_size +
               @@innodb_log_buffer_size +
               @@key_buffer_size +
               @@query_cache_size +
               ( @@max_connections *
                   ( @@binlog_cache_size +
                     @@binlog_stmt_cache_size +
                     @@bulk_insert_buffer_size +
                     @@join_buffer_size +
                     @@net_buffer_length +
                     @@read_buffer_size +
                     @@read_rnd_buffer_size +
                     @@sort_buffer_size +
                     @@thread_stack
                   )
               ) +
               ( @@slave_parallel_threads * 
                 ( @@slave_parallel_max_queued )
               ) +
               ( @@open_files_limit * 1024 )
           ) / 1024 / 1024 / 1024) AS max_memory_GB;
```

tmp_table_size is per table, so the maximum theoretical memory usage related to this setting is incalculable.

Output should be in table format, assuming max_connections = 100:
```
Per connection allocations (max_connections = 100):
+------------------+--------+-----------------------+
| setting          | value  | total (x connections) |
+------------------+--------+-----------------------+
| join_buffer_size | 262144 | 2621440               |
[...]
+------------------+--------+-----------------------+
+ TOTAL            |        | [sum with M/G suffix] |       
+------------------+--------+-----------------------+


Global allocations:
+---------+---------------+-----------+
| setting                 | value     |
+-------------------------+-----------+
| innodb_buffer_pool_size | 134217728 |
[...]
+------------------+--------+-----------------------+
+ TOTAL            |        | [sum with M/G suffix] |
+------------------+--------+-----------------------+
```

If `--verbose` is passed, add this to output:

max_allowed_packet: [size]
Maximum size in bytes of a packet or a generated/intermediate string. The packet message buffer is initialized with the value from net_buffer_length, but can grow up to max_allowed_packet bytes. Has to fit largest query (e.g. large INSERTs for loading mysqldump generated backups) and largest returned payload (while you can cursor through payload one row at a time, large text/blob retrievals still have to fit into max_allowed_packet).
Related: slave_max_allowed_packet for replication purposes (largest transaction has to fit into this size).

While maximum theoretical usage for this allocation is max_allowed_packet x max_connections, this can be absurdly large and should not for part of memory estimate calculations unless your workload is unusual.

tmp_table_size: [size]
This allocation is per table, rather than global or per connection. Since there is no hard limit on how many implicit temporary tables a query could create (e.g., number of CTEs, sub-selects or VIEWs used in a query, though these will not resolve as temporary tables in all cases), maximum memory usage arising from tmp_table_size is incalculable.

**Comment by oblitorum** [comment]
Close as it's completed via https://github.com/shatteredsilicon/silicon-toolkit/pull/14
