### ISSUE TITLE
st-sideload-relay: Unexplained error

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/silicon-toolkit#12]
```
# ./st-sideload-relay --io-thread-threshold=2G                 
Failed to get file size of relay log '/data/log/relay-bin.143762' for channel '': sh: 1: cannot open /data/log/relay-bin.143762: No such file
readline() on closed filehandle $relay_log_fh at ./st-sideload-relay line 682.
```

**Comment by gordan-bobic** [comment]
In the above case, this error was fatal, but now I have just seen it come up twice without being fatal:

```
sleeping 10s because it reaches io-thread-threshold, io-thread-threshold: 2147483648, distance to current end of relay log: 2187047626
Failed to get file size of relay log '/data/log/relay-bin.189383' for channel '': sh: 1: cannot open /data/log/relay-bin.189383: No such file
Failed to get file size of relay log '/data/log/relay-bin.189500' for channel '': sh: 1: cannot open /data/log/relay-bin.189500: No such file
```

**Comment by gordan-bobic** [comment]
Another thing I noticed is that leading up to those errors, `st-sideload-relay` was burning through about 15-20% of CPU while supposedly sleeping, waiting for io-thread-threshold to drop below the threshold where we fetch the next binlog.
But that went away once those two errors above occurred.

**Comment by gordan-bobic** [comment]
Process hasn't failed / exited, but it just emitted another warning like this:
```
sleeping 10s because it reaches io-thread-threshold, io-thread-threshold: 2147483648, distance to current end of relay log: 2187047626
Failed to get file size of relay log '/data/log/relay-bin.189383' for channel '': sh: 1: cannot open /data/log/relay-bin.189383: No such file
Failed to get file size of relay log '/data/log/relay-bin.189500' for channel '': sh: 1: cannot open /data/log/relay-bin.189500: No such file
Failed to get file size of relay log '/data/log/relay-bin.311459' for channel '': sh: 1: cannot open /data/log/relay-bin.311459: No such file
```
Another server on the same replication "cluster" doesn't seem to be triggering it, with the same version of `st-sideload-relay`.

**Comment by oblitorum** [comment]
> Failed to get file size of relay log '/data/log/relay-bin.143762' for channel '': sh: 1: cannot open /data/log/relay-bin.143762: No such file

This one is not fatal, this happens when it tries to sum up the size of all relay log files listed in `relay-bin.index`, and check if it exceeds `relay_log_space_limit`. I think the situation was that those relay log files were deleted after it got the file list from `relay-bin.index`, so the solution would be just ignoring the `No such file` error.

 > readline() on closed filehandle $relay_log_fh at ./st-sideload-relay line 682.

This one is fatal, the responding code for this is

https://github.com/shatteredsilicon/silicon-toolkit/blob/3a28c9968028c77c93755a500ebe0cbac28db4b5/bin/st-sideload-relay#L675-L682

I though if `$EVAL_ERROR` is empty, the filehandle is opened for sure. I just learnt that the return value of `open` should also be checked.

> Another thing I noticed is that leading up to those errors, st-sideload-relay was burning through about 15-20% of CPU while supposedly sleeping, waiting for io-thread-threshold to drop below the threshold where we fetch the next binlog.
But that went away once those two errors above occurred.

You mean the waiting for io-thread-threshold went away after those two errors occurred? It keeps fetching next binlog without waiting after that? That's odd, I couldn't see what could cause this for now.

**Comment by gordan-bobic** [comment]
The message:
```
sleeping 10s because it reaches io-thread-threshold, io-thread-threshold: 2147483648, distance to current end of relay log: 2187047626
```
went away because it is fully caught up, it is fetching binlog in tiny chunks all the time because it is only a few hundred bytes behind all the time. So that part is expected, I think.

**Comment by oblitorum** [comment]
Oh, I see. And it's still functioning after the CPU usage drop spotted? I couldn't see the obvious cause for that either, could it be that the amount of data just got smaller after the first occurrence of that error?

**Comment by oblitorum** [comment]
I created a [PR](https://github.com/shatteredsilicon/silicon-toolkit/pull/14) to adapt these 2 errors for now
```
readline() on closed filehandle $relay_log_fh at ./st-sideload-relay line 682.
```
```
Failed to get file size of relay log '/data/log/relay-bin.189383' for channel '': sh: 1: cannot open /data/log/relay-bin.189383: No such file
```

**Comment by gordan-bobic** [comment]
What set of circumstances can lead to the `No such file` error? Is that a race condition where the relay log gets completed and deleted between when we look it up in the list and get around to examining it?

If so, should we stop the SQL thread while doing this to prevent the race condition? Or is it completely benign and only used for the calculation of whether we sleep for 10 seconds?

**Comment by gordan-bobic** [comment]
On a separate note, I just noticed `wc -c` is used to measure the size of the file. Using `system()` is not a great practice when not necessary, and I suspect using `stat($filename)` would be a cheaper way. If I remember correctly, the size is in array position `[7]` of the return from `stat()`.

**Comment by oblitorum** [comment]
> What set of circumstances can lead to the No such file error? Is that a race condition where the relay log gets completed and deleted between when we look it up in the list and get around to examining it?

Yes, I think that's the exact case. And sure we can stop the SQL thread while calculating the relay log space size, but I don't think that is necessary, isn't it? If the relay log files get deleted during this period, it will only make the relay log space size smaller, we just ignore it, I can't think of what harm can that do.

> On a separate note, I just noticed wc -c is used to measure the size of the file. Using system() is not a great practice when not necessary, and I suspect using stat($filename) would be a cheaper way. If I remember correctly, the size is in array position [7] of the return from stat().

Oh, right, I will fix that. I think there is more straightforward way -> using `-s ${filepath}`

**Comment by gordan-bobic** [comment]
If it is just for relay_log_space limit calculation, that's fine, no need to stop the sql_thread (with parallel replication, that can take a while / cause a long stall).

> Oh, right, I will fix that. I think there is more straightforward way -> using `-s ${filepath}`

Oh, does that work in perl? If it avoids a system() call, it's fine by me.

**Comment by gordan-bobic** [comment]
I jut hit this error again, st-sideload-relay died:
```
readline() on closed filehandle $relay_log_fh at ./st-sideload-relay line 682.
```

**Comment by gordan-bobic** [comment]
Closing this for now, it looks like the last patch fixed it.
