### ISSUE TITLE
pt-visual-explain chokes on some EXPLAIN outputs

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/silicon-toolkit#19]
Reproducer EXPLAIN output is attached.

[pt-visual-explain.error-reproducer.txt](https://github.com/shatteredsilicon/ssm-submodules/files/13256953/pt-visual-explain.error-reproducer.txt)

pt-visual-explain fails with error code 255 and the following output:
```
Use of uninitialized value in concatenation (.) or string at /usr/bin/pt-visual-explain line 682, <> line 1.
```
Affects the current 3.5.5 and our cut down 3.5.1 versions of [Percona Toolkit](https://github.com/percona/percona-toolkit)

Filed upstream here:
https://jira.percona.com/browse/PT-2277

Since we have this raised for .4 release:
https://github.com/shatteredsilicon/ssm-submodules/issues/194 this is low priority, we can just wait for the upstream fix.

**Comment by oblitorum** [comment]
Close this as the fix pushed to upstream is merged via this [PR](https://github.com/percona/percona-toolkit/pull/721), and the patch is now included in our fork -> https://github.com/shatteredsilicon/silicon-toolkit/commit/b2b6311723edbfbd41b3ce77f71e0eec3e37f2b5
