### ISSUE TITLE
st-sideload-relay: Fetch binlogs one by one instead of full prefetch at a time

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/silicon-toolkit#7]
Fetching binlogs takes time - time that the server could be using to execute them. To make better use of fetching time:

1) Fetch the first binlog to the end with the same process as now
2) Make it the relay log
3) Restart the replication

sql_thread should no have something to work with for a little while

4) Stop the io_thread, and fetch the next binlog from the appropriate coordinates
goto 2) until we are above the io-thread-threshold, in the same way we do now

In reality, I think this is only ever going to be a problem on the initial pass around the loop where we are likely to fetch multiple binlogs. Once we hit the io-thread-threshold, each extra pass will only fetch one extra binlog in most cases. Still, it would be nice to avoid this initial waiting overhead if possible.

**Comment by oblitorum** [comment]
Actually, fetching a certain amount of binlog(s) at the initial run is the original design, there is a `--initial_prefetch` parameter for it:

> --initial-prefetch=<int bytes with optional K/M/G/T suffix>, default 2G
>
> Before starting the I/O thread, fetch thos amount of binlog(s) into relay log(s) of appropriate name (look at relay_log / relay_log_basename variables). Can be multiple files. Construct appropriate relay .index file ($relay_log_basename + ".index")

So how about this -> default value for `--initial-prefetch` is none, if its value is given, fetch this amount of binlog(s) at the initial run, otherwise only fetch the first binlog to the end.

**Comment by gordan-bobic** [comment]
I think the key change we need is that we refresh MySQL's view of relay logs after each binlog download completes, not after the full `--initial-prefetch` is completed. That will keep the initial stall time as short as possible.

**Comment by oblitorum** [comment]
Yeah, but that's the whole point of the `--initial-prefetch` parameter. If we refresh MySQL's view of relay logs after each binlog download completes, regardless of what `--initial-prefetch` value is, then this parameter is meaningless, we should probably abandon it.

**Comment by gordan-bobic** [comment]
Oh, I see what you mean! You're right. Let's just have it default to 0. In that case it will still fetch to the end of the upstream binlog, right?

**Comment by oblitorum** [comment]
Yeah, default to `None` or `0`, then only fetch the first binlog to the end. And if its value is given, fetch this amount of binlog(s) at the initial run.

**Comment by gordan-bobic** [comment]
Fair enough. I guess that just means I was using this wrong. :-D

**Comment by oblitorum** [comment]
Wait, it doesn't work this way currently, a patch is needed.

**Comment by oblitorum** [comment]
https://github.com/shatteredsilicon/silicon-toolkit/pull/25
