### ISSUE TITLE
st-sideload-relay: Add --min-lag=<seconds> parameter

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/silicon-toolkit#8]
`--min-lag=<seconds>`
Default: 5

Below this threshold, `st-sideload-relay` should wait in the same way it waits for `--io-thread-threshold` to fall within range.

Reason is that it flaps around in a loop, toggling replication and connections to the master on and off all the time, which while not obviously problematic is a little undesirable as a hysteresis condition. Internal replication should be OK left to its own devices for at least 5 seconds at a time when `st-sideload-relay` already effectively got the replication down to 0.

**Comment by oblitorum** [comment]
Wait, I suppose the `Seconds_Behind_Master` from slave status should be the one we use to measure the lag, right? But this value is set to `NULL` if the io_thread is stopped (at least on Mariadb 10.5.23), and `st-sideload-relay` is meant to stop the io_thread during its execution.

**Comment by gordan-bobic** [comment]
This is specifically for the time where we resume replication and let it replicate itself for a bit. This happens briefly between pulls anyway. The idea is to reduce switching between built in replication and st-sideload-relay by letting built in replication work normally when it is managing to keep up, and only take over when it's natural lag exceeds this threshold.

That means that on a system where replication load is low enough that we don't need st-sideload-relay, it will simply monitor and never take over..

**Comment by oblitorum** [comment]
Oh, I see, then I should add this 'lag check' into a loop at the very beginning, before `st-sideload-relay` tries to stop the io_thread and does its work.

**Comment by gordan-bobic** [comment]
Yes, at the beginning + on each pass of the sideloading loop. If Seconds_Behing_Master <=5, leave MySQL to it's own replication.
